######## 01.INSTALANDO O PACOTE PYTHON NO WINDOWS ########
'''
PASSO 1
    ACESSE: www.python.org

PASSO 2
    CLIQUE EM DOWNLOADS > ESCOLHA A SUA VERSÃO

PASSO 3
    INSTALAÇÃO: 
        EXECUTE O ARQUIVO > MARQUE ADD PYTHON V.xxx TO PATH
            DESABILITAR LIMITE DE COMPRIMENTO DO PATH
                    PRONTO!!!

PASSO 4
    VERIFICANDO A INSTALAÇÃO
        MENU INICIAR > DIGITE: cmd > TECLE ENTER
            NO TERMINAL DIGITE: python -- version > TECLE ENTER
                SE A INSTAÇÃO FUNCIONOU CORRETAMENTE A VERSÃO DO PYTHON DEVE SER EXIBIDA
'''