######## 02. INSTALANDO PACOTES ########
'''
SERVE PARA A INSTALAÇÃO OU DESISTALAÇÃO DE BIBLIOTECAS

PASSO 1
    MENU INICIAR E DIGITE: CMD
        NO TERMINAL DIGITE: PIP LIST (EXIBE A LISTA DE BIBLIOTECAS INSTALADAS)

PASSO 2
    DESISTALANDO BIBLIOTECAS
        PIP UNINSTALL NOME DA BIBLIOTECA
        PROCEDER CONFIRMANDO: Y

PASSO 3
    INSTALANDO UMA BLIBIOTECA
        PIP INSTALL NOME DA BILBIOTECA
'''