############### 05 - STRING DINÂMICO ###############
'''
SERVEM PARA RETORNAR UMA INFORMAÇÃO AO USUÁRIO
    EXEMPLO

PARABÉNS GAFANHOTO, VOCÊ ESTÁ QUASE INSCRITO! ENTRE NO SEU EMAIL gafanhoto@gmail.com E CONFIRME O SEU CADASTRO.
'''
nome_Usuario = 'GAFANHOTO'
email = 'gafanhoto@gmail.com'

print(f'PARABÉNS {nome_Usuario}, VOCÊ ESTÁ QUASE INSCRITO! ENTRE NO SEU EMAIL {email} E CONFIRME O SEU CADASTRO.')