
    ######## 🥇EXERCÍCIO - MÉTODOS PARA STRINGS 🥇 ########
'''
    IMAGINEMOS QUE TEMOS UM CÓDIGO DE DNA ABAIXO E GOSTARÍAMOS DE EDITÁLO DA SEGUINTE FORMA:
        1. PADRONIZANDO O TAMANHO DA FONTE
            A. TUDO EM CAIXA ALTA
            B. TUDO EM CAIXA BAIXA
        2. REMOVENDO ESPAÇOS EM BRANCO DA REPRESENTAÇÃO DE UM GENE
            A. DA DIREITA
            B. DA ESQUERDA
            C. DA DIREITA E DA ESQUERDA
        3.REMOVENDO CODONS DE UM GENE
            A. REMOVER CODON DE INÍCIO (AaA)
            B. REMOVER CODON DE PARADA (TTT)
            C. EXIBINDO APENAS O GENE SEM OS CÓDONS DE INÍCIO (AaA) E DE PARADA (TTT)        
'''
DNA = '        AaATTTGGGcCATgCTAttCcGGTAACgGaTTT '