######## 🥇 RESOLUÇÃO - MÉTODOS PARA STRINGS 🥇 ########
'''
    IMAGINEMOS QUE TEMOS UM CÓDIGO DE DNA ABAIXO E GOSTARÍAMOS DE EDITÁLO DA SEGUINTE FORMA:
        1. PADRONIZANDO O TAMANHO DA FONTE
            A. TUDO EM CAIXA ALTA
            B. TUDO EM CAIXA BAIXA
        2. REMOVENDO ESPAÇOS EM BRANCO DA REPRESENTAÇÃO DE UM GENE
            A. DA DIREITA
            B. DA ESQUERDA
            C. DA DIREITA E DA ESQUERDA
        3.REMOVENDO CODONS DE UM GENE
            A. REMOVER CODON DE INÍCIO (AaA)
            B. REMOVER CODON DE PARADA (TTT)
            C. EXIBINDO APENAS O GENE SEM OS CÓDONS DE INÍCIO (AaA) E DE PARADA (TTT)        
'''
DNA = '        AaATTTGGGcCATgCTAttCcGGTAACgGaTTT '

print(DNA.upper()) # FONTE MAIÚSCULA
print(DNA.lower()) # FONTE MINÚSCULA

print(DNA.rstrip()) # REMOVENDO ESPAÇOS EM BRANCO À DIREITA DE UM GENE
print(DNA.lstrip()) # REMOVENDO ESPAÇOS EM BRANCO À ESQUERDA
print(DNA.strip())  # REMOVENDO ESPAÇOS EM BRANCO À DIREITA E À ESQUERDA

print(DNA.strip().rstrip('TTT')) # 3.REMOVENDO CODON À DIREITA DE UM GENE
print(DNA.strip().lstrip('AaA')) # REMOVENDO CODON À ESQUERDA
print(DNA.strip().lstrip('AaA').rstrip('TTT')) # 3.REMOVENDO CODONS À DIREITA E À ESQUERDA