############### 12 - ATALHOS DO VS CODE ###############
'''
IMPORTÂNCIA:
    CONSEGUIR TRABALHAR MAIS RÁPIDO E DE FORMA MAIS EFICIÊNTE.
   
    EXEMPLO:
'''
'''
COMENTAR UMA LINHA
'''
    CTRL + K + C
'''
DESCOMENTAR UMA LINHA
'''
    CTRL + K + U
'''
COMENTAR E DESCOMENTAR VÁRIAS LINHAS
'''
    SHIFT + ALT + A
'''
MOVIMENTAR UM CÓDIGO PARA CIMA OU PARA BAIXO
'''
    ALT + SETA PARA BAIXO OU PARA CIMA
'''
REMOVE OU REEXIBE A BARRA LATERAL ESQUERDA (EXPLORER)
'''
    CTRL + B
'''
REMOVE OU REEXIBE O TERMINAL
'''
    CTRL + "
'''
ENCONTRAR E SUBSTITUIR UM TERMO DO SEU CÓDIGO
'''
    CTRL + F # ENTRAR COM O TEXTO
    CTRL + H # ENTRAR COM O NOVO TEXTO
    CTRL + ALT + ENTER # SUBSTITUIR O TEXTO ANTIGO PELO NOVO
'''
ALTERNAR ENTRE ARQUIVOS DO VS CODE
'''
    CTRL + P
'''
ALTERNANDO ENTRE JANELAS
'''
    CTRL + 1
    CTRL + 2
'''
FECHA A JANELA ATUAL
'''
    CTRL + W