############### 15 - LEI DE PARETTO 🥇 ###############
'''
IMPORTÂNCIA:

EXPLICA A IMPORTÂNCIA DE VOCÊ DOCUMENTAR O SEU APRENDIZADO E TRANSMITÍ-LO PARA OUTRO.
ISSO ACELERA SEU APRENDIZADO EM MAIS 500%
'''

'''
CRIAR UM CANAL NO YOUTUBE EXPLICANDO O QUE EU APRENDI SOBRE PYTHON
'''